#pragma once

#define VERSION_MAJOR    1
#define VERSION_MINOR    1
#define VERSION_PATCH    0
#define VERSION_BUILD    0

#define STRINGIFY2(x)    #x
#define STRINGIFY(x)     STRINGIFY2(x)

#define VERSION_STR      STRINGIFY(VERSION_MAJOR) "." STRINGIFY(VERSION_MINOR) "." STRINGIFY(VERSION_PATCH)
#define VERSION_STR_FULL STRINGIFY(VERSION_MAJOR) "." STRINGIFY(VERSION_MINOR) "." STRINGIFY(VERSION_PATCH) "." STRINGIFY(VERSION_BUILD)
